services:
  api:
    build: ./api
    ports:
      - "4000:4000"
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - api
  recommend:
    build: ./recommend_service
    ports:
      - "8000:8000"